import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — PhenoSage",
  description: "Terms of service for the PhenoSage plant-health platform.",
};

const LAST_UPDATED = "June 11, 2026";

export default function TermsPage() {
  return (
    <>
      <h1>Terms of Service</h1>
      <p>Last updated: {LAST_UPDATED}</p>

      <h2>1. What PhenoSage is</h2>
      <p>
        PhenoSage is a plant-health journaling and analysis tool for legal home
        and licensed cultivators. You upload photos and notes about your plants;
        the service stores them, runs AI-assisted image analysis, and gives you
        findings, trends, and chat-based guidance.
      </p>

      <h2>2. Eligibility and legal compliance</h2>
      <ul>
        <li>
          You must be of legal age to cultivate cannabis in your jurisdiction —
          21 or older where that is the threshold, and never younger than 18.
        </li>
        <li>
          Cannabis cultivation is illegal or restricted in many places. You are
          solely responsible for knowing and complying with the laws that apply
          to you. PhenoSage does not provide legal advice and does not encourage
          cultivation where it is unlawful.
        </li>
        <li>
          You may not use the service on behalf of anyone who does not meet
          these requirements.
        </li>
      </ul>

      <h2>3. AI output is not professional advice</h2>
      <p>
        Findings, health scores, and chat responses are generated by AI models
        and can be wrong, incomplete, or inapplicable to your situation. They
        are informational only. When an image cannot be analyzed reliably, the
        service reports an inconclusive result rather than guessing — treat
        every result as a starting point for your own judgment, not a diagnosis.
      </p>

      <h2>4. Your content</h2>
      <p>
        You keep ownership of the photos and notes you upload. You grant
        PhenoSage the rights needed to store and process them to operate the
        service, including sending images to third-party AI providers for
        analysis (see the Privacy Policy). You are responsible for what you
        upload; do not upload content that is unlawful or that you lack rights
        to.
      </p>

      <h2>5. Acceptable use</h2>
      <ul>
        <li>No attempts to breach, probe, or overload the service.</li>
        <li>
          No automated scraping or bulk submission beyond documented limits —
          analysis requests are rate-limited and quota-capped per account.
        </li>
        <li>No use of the service to facilitate unlawful activity.</li>
      </ul>

      <h2>6. Availability and changes</h2>
      <p>
        The service is provided “as is” without warranties. We may change,
        suspend, or discontinue features, and may update these terms; material
        changes will be reflected on this page with a new “last updated” date.
        Continued use after a change means you accept it.
      </p>

      <h2>7. Limitation of liability</h2>
      <p>
        To the maximum extent permitted by law, PhenoSage is not liable for crop
        loss, indirect or consequential damages, or losses arising from reliance
        on AI-generated output or from your failure to comply with local law.
      </p>

      <h2>8. Termination</h2>
      <p>
        You can stop using the service at any time and request deletion of your
        account and data (see the Privacy Policy). We may suspend or terminate
        accounts that violate these terms.
      </p>

      <h2>9. Contact</h2>
      <p>
        Questions about these terms: open an issue on the project repository or
        contact the operator at the address published there.
      </p>

      <p>
        <em>
          Note: this document is a general template provided in good faith and
          has not been reviewed by counsel. Before a public commercial launch,
          have it reviewed by a lawyer familiar with your jurisdiction.
        </em>
      </p>
    </>
  );
}
